### ISSUE TITLE
[BUG] README inconsistent with latest versions

### ISSUE THREAD

**Issue by palladius** [Mirascope/mirascope-cli#3]
$ mirascope init --mirascope_location my_mirascope --prompts_location calls
Usage: mirascope init [OPTIONS]
Try 'mirascope init --help' for help.
╭─ Error ──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
│ No such option: --mirascope_location Did you mean --mirascope-location?                                                                                  │
╰────────────────────────────────────────────────────────────────────────────────────────────────

I say this because I'm not able to get through the whole `README.md` and get the test prompt to run.

**Comment by willbakst** [comment]
Ah, yeah this is an issue with the documentation, it should be `--mirascope-location`

I've updated the README so it's correct.

It's worth noting that we have not tested this CLI with the newest `v1` release of Mirascope.

We are working on a separate prompt versioning/management library that we will be releasing soon to replace this one. Stay tuned :)
